package br.uff.ic.gems.peixeespadacliente.gui;

import br.uff.ic.gems.peixeespadacliente.model.agent.LocalManagerAgent;
import br.uff.ic.oceano.core.exception.ServiceException;
import br.uff.ic.gems.peixeespadacliente.service.ClientService;
import br.uff.ic.oceano.peixeespada.model.Agent;
import br.uff.ic.oceano.core.factory.ObjectFactory;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Heliomar
 */
public class JChooseOrchestratorAgent extends javax.swing.JInternalFrame {

    private JInternalFrame parent;
    private ClientService clientServer = ObjectFactory.getObjectWithoutDataBaseDependencies(ClientService.class);
    private LocalManagerAgent agentPeixeEspada;

    /** Creates new form ChooseOrchestratorAgent */
    public JChooseOrchestratorAgent(List<Agent> orchestradorAgents, JInternalFrame parent, LocalManagerAgent agentPeixeEspada) {
        initComponents();
        for (Agent agent : orchestradorAgents) {
            DefaultComboBoxModel model = (DefaultComboBoxModel) jComboAgents.getModel();
            model.addElement(agent);
        }
        this.parent = parent;
        this.agentPeixeEspada = agentPeixeEspada;
        parent.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnScheduling = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jComboAgents = new javax.swing.JComboBox();

        setTitle("Choose the Orchestrator Agent");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Action"));

        btnScheduling.setText("OK");
        btnScheduling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSchedulingActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnScheduling)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnScheduling)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboAgents.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose the Orchestrator Agent" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jComboAgents, 0, 279, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jComboAgents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSchedulingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSchedulingActionPerformed
        // TODO add your handling code here:
        Object selected = jComboAgents.getSelectedItem();
        if (!(selected instanceof Agent)) {
            JOptionPane.showMessageDialog(this, "Choose a Orchestrator Agent", "Validation error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        agentPeixeEspada.prepareAgent((Agent) selected);

        try {
            // scheduling
            clientServer.scheduling(agentPeixeEspada);
            JOptionPane.showMessageDialog(this, "Agent: [" + agentPeixeEspada.getIdentifier() + "] registred with sucessfull", "Sucessfull", JOptionPane.INFORMATION_MESSAGE);
            Main.jDesktop.add(agentPeixeEspada.prepareOutput());
            parent.dispose();
            this.dispose();
        } catch (ServiceException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Validation error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSchedulingActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnScheduling;
    private javax.swing.JComboBox jComboAgents;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
